import { useCallback, useEffect, useMemo, useState } from "react";
import type { BudgetCadence, CostGroupBy, CostPeriodPreset, CostSummary, ProviderImportMapping, ProviderImportPreview, ProxyProfile, ReconciliationStatus } from "@copify/shared";
import { Field } from "../ui/primitives";

const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC";
const usd=(value:number|null)=>value===null?"Unavailable":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:4,maximumFractionDigits:6}).format(value/1_000_000);
const bytes=(value:number)=>value>=1_000_000_000?`${(value/1_000_000_000).toFixed(2)} GB`:`${(value/1_000_000).toFixed(2)} MB`;
const dateInput=(timestamp:number)=>new Date(timestamp).toISOString().slice(0,10);

export function Costs({proxies}:{proxies:ProxyProfile[]}){
  const providers=useMemo(()=>[...new Set(proxies.map((proxy)=>proxy.provider))].sort(),[proxies]);
  const [preset,setPreset]=useState<CostPeriodPreset>("TODAY"); const [groupBy,setGroupBy]=useState<CostGroupBy>("PROVIDER"); const [provider,setProvider]=useState<string>(""); const [customStart,setCustomStart]=useState(dateInput(Date.now()-86_400_000));const[customEnd,setCustomEnd]=useState(dateInput(Date.now()+86_400_000));
  const [summary,setSummary]=useState<CostSummary|null>(null);const[reconciliation,setReconciliation]=useState<ReconciliationStatus|null>(null);const[notice,setNotice]=useState("");const[importPreview,setImportPreview]=useState<ProviderImportPreview|null>(null);
  const [manual,setManual]=useState<{provider:string;start:string;end:string;trafficGb:string;spendUsd:string;creditUsd:string}>({provider:providers[0]??"dataimpulse",start:dateInput(Date.now()-86_400_000),end:dateInput(Date.now()),trafficGb:"",spendUsd:"",creditUsd:""});
  const [budget,setBudget]=useState<{provider:string;cadence:BudgetCadence;limitUsd:string;startingCreditUsd:string;hardCap:boolean;enabled:boolean}>({provider:providers[0]??"dataimpulse",cadence:"MONTHLY",limitUsd:"10",startingCreditUsd:"",hardCap:false,enabled:true});
  const load=useCallback(async()=>{const startAt=preset==="CUSTOM"?new Date(`${customStart}T00:00:00`).getTime():null;const endAt=preset==="CUSTOM"?new Date(`${customEnd}T23:59:59.999`).getTime():null;const result=await window.copify.costs.query({period:{preset,startAt,endAt,timezoneId:timezone},groupBy,provider:provider||null});if(result.ok)setSummary(result.value);else setNotice(result.error);const history=await window.copify.costs.reconciliation(provider||undefined);if(history.ok)setReconciliation(history.value);},[preset,customStart,customEnd,groupBy,provider]);
  useEffect(()=>{void load();return window.copify.costs.onChanged(()=>void load());},[load]);
  const saveManual=async(event:React.FormEvent)=>{event.preventDefault();const result=await window.copify.costs.manualSnapshot({provider:manual.provider as ProxyProfile["provider"],intervalStartAt:new Date(`${manual.start}T00:00:00`).getTime(),intervalEndAt:new Date(`${manual.end}T23:59:59.999`).getTime(),usedBytes:manual.trafficGb?Math.round(Number(manual.trafficGb)*1_000_000_000):null,requestCount:null,billedCostMicrosUsd:manual.spendUsd?Math.round(Number(manual.spendUsd)*1_000_000):null,remainingCreditMicrosUsd:manual.creditUsd?Math.round(Number(manual.creditUsd)*1_000_000):null});setNotice(result.ok?"Manual provider snapshot saved.":result.error);if(result.ok)void load();};
  const removeManual=async(id:string)=>{if(!window.confirm("Remove this manual usage and spend snapshot? Imported provider records and remaining-credit snapshots are not changed."))return;const result=await window.copify.costs.removeManualSnapshot(id);setNotice(result.ok&&result.value?"Manual usage snapshot removed.":result.ok?"That manual snapshot was already removed.":result.error);if(result.ok)void load();};
  const openImport=async()=>{const result=await window.copify.costs.importOpen(provider||manual.provider);if(!result.ok)setNotice(result.error);else if(result.value)setImportPreview(result.value);};
  const setMapping=(key:keyof ProviderImportMapping,value:string|null)=>{if(!importPreview?.mapping)return;const mapping={...importPreview.mapping,[key]:value};void window.copify.costs.importPreview(importPreview.token,mapping).then((result)=>result.ok?setImportPreview(result.value):setNotice(result.error));};
  const commitImport=async()=>{if(!importPreview?.mapping)return;const result=await window.copify.costs.importCommit(importPreview.token,importPreview.mapping);setNotice(result.ok?(result.value.duplicate?"This normalized report was already imported.":`Imported ${result.value.rowCount} confirmed rows.`):result.error);if(result.ok){setImportPreview(null);void load();}};
  const saveBudget=async(event:React.FormEvent)=>{event.preventDefault();const result=await window.copify.costs.upsertBudget({provider:budget.provider as ProxyProfile["provider"],cadence:budget.cadence,limitMicrosUsd:Math.round(Number(budget.limitUsd)*1_000_000),startingCreditMicrosUsd:budget.startingCreditUsd?Math.round(Number(budget.startingCreditUsd)*1_000_000):null,timezoneId:timezone,thresholds:[50,80,100],hardCap:budget.hardCap,enabled:budget.enabled});setNotice(result.ok?"Budget saved.":result.error);if(result.ok)void load();};
  return <div className="page-stack">
    <section className="panel"><div className="section-title"><div><h2>Costs & budgets</h2><p className="muted">Copify estimates and provider-confirmed figures stay separate. Period timezone: {timezone}.</p></div><button onClick={()=>void load()}>Refresh</button></div>
      <div className="run-form"><Field label="Period"><select value={preset} onChange={(e)=>setPreset(e.target.value as CostPeriodPreset)}><option value="TODAY">Today</option><option value="LAST_24_HOURS">Last 24 hours</option><option value="ROLLING_7_DAYS">Rolling 7 days</option><option value="CALENDAR_MONTH">Calendar month</option><option value="CUSTOM">Custom</option></select></Field><Field label="Break down by"><select value={groupBy} onChange={(e)=>setGroupBy(e.target.value as CostGroupBy)}>{["PROVIDER","PROXY","STORE","SOURCE","BROWSER_PROFILE","RUN"].map((value)=><option key={value}>{value}</option>)}</select></Field><Field label="Provider"><select value={provider} onChange={(e)=>setProvider(e.target.value)}><option value="">All providers</option>{providers.map((value)=><option key={value}>{value}</option>)}</select></Field>{preset==="CUSTOM"&&<><Field label="Start"><input type="date" value={customStart} onChange={(e)=>setCustomStart(e.target.value)}/></Field><Field label="End"><input type="date" value={customEnd} onChange={(e)=>setCustomEnd(e.target.value)}/></Field></>}</div>
    </section>
    {summary&&<><section className="panel"><div className="rows">
      <CostCard name="Copify estimate" value={usd(summary.estimatedCostMicrosUsd)} meta="Observed application bytes"/><CostCard name="Confirmed spend" value={usd(summary.confirmedCostMicrosUsd)} meta={summary.confirmedAuthority===null?"No confirmed interval":summary.confirmedDifferenceMicrosUsd===null?`${summary.confirmedAuthority} · partial confirmed range`:summary.confirmedAuthority}/><CostCard name="Proxy traffic" value={bytes(summary.receivedBytes+summary.sentBytes)} meta={`${summary.requestCount.toLocaleString()} requests`}/><CostCard name="Remaining credit" value={usd(summary.remainingCreditMicrosUsd)} meta={summary.confirmedDataAgeMs===null?"No provider snapshot":`${Math.round(summary.confirmedDataAgeMs/3_600_000)}h old`}/><CostCard name="Estimate coverage" value={summary.estimationCoverage===null?"Unavailable":`${(summary.estimationCoverage*100).toFixed(1)}%`} meta={summary.confirmedDifferenceMicrosUsd===null?"No comparable confirmed range":`Difference ${usd(summary.confirmedDifferenceMicrosUsd)}`}/>
      </div>{summary.confirmedDataAgeMs!==null&&summary.confirmedDataAgeMs>86_400_000&&<p className="warning">Provider-confirmed data is more than 24 hours old. Budget enforcement may be using Copify estimates.</p>}</section><section className="panel"><div className="section-title"><div><h2>Breakdown</h2><p className="muted">Complete, partial, and unavailable map to the wire values EXACT, PARTIAL, and UNSUPPORTED.</p></div></div><div className="rows">{summary.rows.map((row)=><div className="row" key={row.id}><span className="row-main"><span className="row-name">{row.label}</span><span className="row-meta">{bytes(row.receivedBytes+row.sentBytes)} · {row.requestCount.toLocaleString()} requests · {row.completeness.toLowerCase()}</span></span><span className="row-cell mono">{usd(row.estimatedCostMicrosUsd)}</span><span className="row-cell mono">{usd(row.confirmedCostMicrosUsd)}</span></div>)}{!summary.rows.length&&<div className="empty">No cost-ledger traffic in this period.</div>}</div></section></>}
    <section className="panel"><div className="section-title"><div><h2>Provider reconciliation</h2><p className="muted">CSV contents and local paths remain in the main process and are never stored.</p></div><button onClick={()=>void openImport()}>Import CSV</button></div>
      {importPreview&&<div className="card"><p>{importPreview.totalRows.toLocaleString()} rows · {importPreview.rejectedRows.toLocaleString()} rejected · {importPreview.spendRowCount.toLocaleString()} with billed spend · token expires {new Date(importPreview.expiresAt).toLocaleTimeString()}</p>{importPreview.warnings.map((warning)=><p className="warning" key={warning}>{warning}</p>)}{importPreview.mapping?<div className="run-form">{(["timestampColumn","endTimestampColumn","trafficColumn","requestCountColumn","costColumn","planColumn"] as const).map((key)=><Field key={key} label={key}><select value={importPreview.mapping?.[key]??""} onChange={(e)=>setMapping(key,e.target.value||null)}><option value="">Not mapped</option>{importPreview.headers.map((header)=><option key={header.id} value={header.label}>{header.label}</option>)}</select></Field>)}<Field label="Traffic unit"><select value={importPreview.mapping.trafficUnit} onChange={(e)=>setMapping("trafficUnit",e.target.value)}>{["BYTES","KB","MB","GB"].map((unit)=><option key={unit}>{unit}</option>)}</select></Field></div>:<p className="warning">Map the report fields explicitly.</p>}<button disabled={!importPreview.mapping} onClick={()=>void commitImport()}>Commit normalized rows</button> <button onClick={()=>{void window.copify.costs.importCancel(importPreview.token);setImportPreview(null);}}>Cancel</button></div>}
      <form className="run-form" onSubmit={saveManual}><Field label="Provider"><select value={manual.provider} onChange={(e)=>setManual({...manual,provider:e.target.value})}>{providers.map((value)=><option key={value}>{value}</option>)}</select></Field><Field label="Range start"><input type="date" value={manual.start} onChange={(e)=>setManual({...manual,start:e.target.value})}/></Field><Field label="Range end"><input type="date" value={manual.end} onChange={(e)=>setManual({...manual,end:e.target.value})}/></Field><Field label="Used traffic (GB)"><input type="number" min="0" step="0.001" value={manual.trafficGb} onChange={(e)=>setManual({...manual,trafficGb:e.target.value})}/></Field><Field label="Billed spend (USD)"><input type="number" min="0" step="0.000001" value={manual.spendUsd} onChange={(e)=>setManual({...manual,spendUsd:e.target.value})}/></Field><Field label="Remaining credit (USD)"><input type="number" min="0" step="0.000001" value={manual.creditUsd} onChange={(e)=>setManual({...manual,creditUsd:e.target.value})}/></Field><button>Save manual snapshot</button></form>
      <div className="rows">{reconciliation?.usage.filter((entry)=>entry.authority==="MANUAL_CONFIRMED").map((entry)=><div className="row" key={entry.id}><span className="row-main"><span className="row-name">Manual {entry.provider} snapshot</span><span className="row-meta">{new Date(entry.intervalStartAt).toLocaleDateString()} – {new Date(entry.intervalEndAt).toLocaleDateString()} · {entry.receivedBytes===null?"traffic unavailable":bytes(entry.receivedBytes)} · {new Date(entry.recordedAt).toLocaleString()}</span></span><span className="row-cell mono">{usd(entry.billedCostMicrosUsd)}</span><button className="danger-link" onClick={()=>void removeManual(entry.id)}>Remove</button></div>)}</div>
      <div className="rows">{reconciliation?.imports.map((batch)=><div className="row" key={batch.id}><span className="row-main"><span className="row-name">{batch.provider} CSV import</span><span className="row-meta">{batch.rowCount.toLocaleString()} rows · {batch.spendRowCount?`${batch.spendRowCount.toLocaleString()} spend values`:"no spend values"} · {new Date(batch.importedAt).toLocaleString()}</span></span><span className="row-cell mono">{usd(batch.billedCostMicrosUsd)}</span></div>)}</div>
    </section>
    <section className="panel"><div className="section-title"><div><h2>Provider budgets</h2><p className="muted">Weeks begin Monday. Hard caps affect new monitor requests only, never checkout browsers.</p></div></div>{providers.length?<><form className="run-form" onSubmit={saveBudget}><Field label="Provider"><select value={budget.provider} onChange={(e)=>setBudget({...budget,provider:e.target.value})}>{providers.map((value)=><option key={value}>{value}</option>)}</select></Field><Field label="Cadence"><select value={budget.cadence} onChange={(e)=>setBudget({...budget,cadence:e.target.value as BudgetCadence})}>{["DAILY","WEEKLY","MONTHLY"].map((value)=><option key={value}>{value}</option>)}</select></Field><Field label="Limit (USD)"><input required type="number" min="0.000001" step="0.000001" value={budget.limitUsd} onChange={(e)=>setBudget({...budget,limitUsd:e.target.value})}/></Field><Field label="Starting credit (USD, optional)"><input type="number" min="0" step="0.000001" value={budget.startingCreditUsd} onChange={(e)=>setBudget({...budget,startingCreditUsd:e.target.value})}/></Field><label className="check"><input type="checkbox" checked={budget.hardCap} onChange={(e)=>setBudget({...budget,hardCap:e.target.checked})}/> Stop new provider monitor requests at 100%</label><label className="check"><input type="checkbox" checked={budget.enabled} onChange={(e)=>setBudget({...budget,enabled:e.target.checked})}/> Enabled</label><button>Save budget</button></form><div className="rows">{summary?.budgets.map((status)=><div className="row" key={status.budget.id}><span className="row-main"><span className="row-name">{status.budget.provider} · {status.budget.cadence.toLowerCase()}</span><progress value={Math.min(status.percent,100)} max={100}/><span className="row-meta">{status.authority} · resets {new Date(status.periodEndAt).toLocaleString()} · alerts {status.firedThresholds.join(", ")||"none"}</span></span><span className={`row-cell mono ${status.capped?"danger":""}`}>{status.percent.toFixed(1)}% · {usd(status.spentMicrosUsd)}</span></div>)}</div></>:<div className="empty">Add a proxy provider before creating a provider budget.</div>}</section>
    {notice&&<p className="field-note">{notice}</p>}
  </div>;
}
function CostCard({name,value,meta}:{name:string;value:string;meta:string}){return <div className="row"><span className="row-main"><span className="row-name">{name}</span><span className="row-meta">{meta}</span></span><span className="row-cell mono">{value}</span></div>;}
