import { useState } from "react";
import type { BrowserProfile, CreatePaymentProfileInput, PaymentBatchPreview, PaymentProfile } from "@copify/shared";
import { Field } from "../ui/primitives";

const blank = (): CreatePaymentProfileInput => ({ name: "", kind: "CARD", cardNumber: "", expiryMonth: 1, expiryYear: new Date().getFullYear() + 1, cvv: "", cardholderName: "", tags: [], billing: null });

export function Payments({ profiles, payments, activeRun, busy, onCreate, onUpdate, onRemove, onAssign }: { profiles: BrowserProfile[]; payments: PaymentProfile[]; activeRun: boolean; busy: boolean; onCreate: (input: CreatePaymentProfileInput) => Promise<boolean>; onUpdate: (id:string,input:import("@copify/shared").UpdatePaymentProfileInput)=>Promise<boolean>; onRemove: (profile: PaymentProfile) => void; onAssign: (browserId: string, paymentId: string) => void }) {
  const [draft, setDraft] = useState<CreatePaymentProfileInput>(blank());
  const [editingId,setEditingId]=useState<string|null>(null);
  const [paste, setPaste] = useState(""); const [preview, setPreview] = useState<PaymentBatchPreview | null>(null); const [error, setError] = useState("");
  const previewPaste = async () => { const value = paste; setPaste(""); const response = await window.copify.payments.previewPaste(value); if (!response.ok) setError(response.error); else { setError(""); setPreview(response.value); } };
  const importCsv = async () => { const response = await window.copify.payments.previewCsv(); if (!response.ok) setError(response.error); else if (response.value) { setError(""); setPreview(response.value); } };
  const commit = async () => { if (!preview) return; const selections = preview.rows.filter((row) => row.errors.length === 0).map((row) => ({ rowNumber: row.rowNumber, includeWarnings: row.warnings.length > 0, browserProfileId: null })); const response = await window.copify.payments.commitBatch({ token: preview.token, selections }); if (!response.ok) setError(response.error); else { setPreview(null); setError(""); } };
  return <div className="page-stack">
    <section className="panel"><div className="section-title"><div><h2>Payment Profiles</h2><p className="muted">Encrypted card details are write-only. Copify never reveals or copies saved PAN or CVV.</p></div></div>
      <div className="rows"><div className="row row-head"><span>Name</span><span>Card</span><span>Expiry</span><span /></div>{payments.map((item)=><div className="row" key={item.id}><span className="row-name">{item.name}</span><span>{item.brand ?? item.kind} •••• {item.last4 ?? "—"}</span><span>{item.expiryMonth && item.expiryYear ? `${String(item.expiryMonth).padStart(2,"0")}/${item.expiryYear}` : "—"}</span><span><button disabled={busy||activeRun} onClick={()=>{setEditingId(item.id);setDraft({...blank(),name:item.name,kind:item.kind==="VCC"?"VCC":"CARD",tags:item.tags});}}>Replace secret</button><button disabled={busy||activeRun} onClick={()=>{const name=window.prompt("Payment Profile name",item.name)?.trim();if(name)void onUpdate(item.id,{name});}}>Rename</button><button disabled={busy||activeRun} onClick={()=>onRemove(item)}>Remove</button></span></div>)}</div>
      {!payments.length&&<div className="empty">No payment profiles yet.</div>}
    </section>
    <section className="panel"><h2>{editingId?"Replace encrypted secret":"Add CARD/VCC"}</h2><form className="drawer-form" onSubmit={async(e)=>{e.preventDefault();const completed=editingId?await onUpdate(editingId,{replacement:{kind:draft.kind,cardNumber:draft.cardNumber,expiryMonth:draft.expiryMonth,expiryYear:draft.expiryYear,cvv:draft.cvv,cardholderName:draft.cardholderName,billing:draft.billing}}):await onCreate(draft);if(completed){setDraft(blank());setEditingId(null);}}}>
      <Field label="Name"><input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field>
      <Field label="Kind"><select value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value as "CARD"|"VCC"})}><option value="CARD">Card</option><option value="VCC">VCC</option></select></Field>
      <Field label="Card number"><input required inputMode="numeric" autoComplete="off" value={draft.cardNumber} onChange={e=>setDraft({...draft,cardNumber:e.target.value})}/></Field>
      <Field label="Expiry month"><input required type="number" min="1" max="12" value={draft.expiryMonth} onChange={e=>setDraft({...draft,expiryMonth:Number(e.target.value)})}/></Field>
      <Field label="Expiry year"><input required type="number" min={new Date().getFullYear()} value={draft.expiryYear} onChange={e=>setDraft({...draft,expiryYear:Number(e.target.value)})}/></Field>
      <Field label="CVV"><input required type="password" inputMode="numeric" autoComplete="off" value={draft.cvv} onChange={e=>setDraft({...draft,cvv:e.target.value})}/></Field>
      <Field label="Cardholder"><input required value={draft.cardholderName} onChange={e=>setDraft({...draft,cardholderName:e.target.value})}/></Field>
      <Field label="Tags"><input value={(draft.tags??[]).join(" | ")} onChange={e=>setDraft({...draft,tags:e.target.value.split("|").map(v=>v.trim()).filter(Boolean)})} placeholder="Revolut | MB WAY"/></Field>
      <label className="check"><input type="checkbox" checked={Boolean(draft.billing)} onChange={e=>setDraft({...draft,billing:e.target.checked?{fullName:draft.cardholderName||"Cardholder",address1:"",postalCode:"",city:"",country:"PT"}:null})}/>Use a billing address different from the assigned Shipping Profile</label>
      {draft.billing&&<><Field label="Billing address"><input required value={draft.billing.address1} onChange={e=>setDraft({...draft,billing:{...draft.billing!,address1:e.target.value}})}/></Field><Field label="Billing address line 2"><input value={draft.billing.address2??""} onChange={e=>setDraft({...draft,billing:{...draft.billing!,address2:e.target.value||undefined}})}/></Field><Field label="Billing postal code"><input required value={draft.billing.postalCode} onChange={e=>setDraft({...draft,billing:{...draft.billing!,postalCode:e.target.value}})}/></Field><Field label="Billing city"><input required value={draft.billing.city} onChange={e=>setDraft({...draft,billing:{...draft.billing!,city:e.target.value}})}/></Field><Field label="Billing region"><input value={draft.billing.region??""} onChange={e=>setDraft({...draft,billing:{...draft.billing!,region:e.target.value||undefined}})}/></Field><Field label="Billing country"><input required maxLength={2} value={draft.billing.country} onChange={e=>setDraft({...draft,billing:{...draft.billing!,country:e.target.value.toUpperCase()}})}/></Field></>}
      <button className="primary" disabled={busy||activeRun}>{editingId?"Replace encrypted secret":"Save encrypted profile"}</button>{editingId&&<button type="button" onClick={()=>{setEditingId(null);setDraft(blank());}}>Cancel</button>}
    </form></section>
    <section className="panel"><div className="section-title"><div><h2>Secure batch intake</h2><p className="muted">CSV is parsed only in the main process; pasted plaintext is cleared immediately after preview.</p></div><button disabled={busy||activeRun} onClick={()=>void importCsv()}>Choose CSV</button></div>
      <textarea rows={5} value={paste} onChange={e=>setPaste(e.target.value)} placeholder="Paste headered CSV"/><button disabled={!paste||busy||activeRun} onClick={()=>void previewPaste()}>Preview paste</button>
      {preview&&<div><p>{preview.rows.length} row(s), expires in two minutes.</p>{preview.rows.map(row=><p key={row.rowNumber}>Row {row.rowNumber}: {row.name||"Unnamed"} •••• {row.last4??"—"} — {row.errors.length?row.errors.join(", "):row.warnings.length?row.warnings.join(", "):"Ready"}</p>)}<button className="primary" disabled={!preview.rows.some(r=>!r.errors.length)} onClick={()=>void commit()}>Import valid rows</button></div>}{error&&<p className="error-detail">{error}</p>}
    </section>
    <section className="panel"><h2>Browser assignments</h2>{profiles.map(profile=><div className="row" key={profile.id}><span>{profile.name}</span><select disabled={busy||activeRun} value={profile.paymentProfileId??""} onChange={e=>onAssign(profile.id,e.target.value)}><option value="">None</option>{payments.filter(p=>p.configured&&p.kind!=="GATEWAY_TOKEN").map(p=><option key={p.id} value={p.id}>{p.name} •••• {p.last4}</option>)}</select></div>)}</section>
    <section className="panel security-warning"><h2>Compliance exception</h2><p>Copify v0.14 stores CVV encrypted for future checkout. PCI SSC states that card verification codes must not be retained after authorization, even when encrypted. Obtain specialist PCI/legal review before distribution.</p></section>
  </div>;
}
