import { createServer } from "node:http";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { chromium } from "rebrowser-playwright";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { findChromeExecutable } from "./network";
import { fillShipping, goToCheckout, inspectBrowserCartDocument, parseShopifyCart, submitDirectCart, waitForExactVisibleCart } from "./runner";

const enabled = process.env.COPIFY_DIRECT_CART_SMOKE === "1";
describe.skipIf(!enabled)("verified direct-cart smoke", () => {
  let origin = ""; let profile = ""; let close: (() => Promise<void>) | undefined; let carted = false; let cartVisibleAt = 0; let cartDelayMs = 0; let addStatus = 200; let addAttempts = 0;
  beforeAll(async () => { const server = createServer((request, response) => { if (request.url === "/cart/add.js" && request.method === "POST") { addAttempts += 1; if (addStatus === 200) { carted = true; cartVisibleAt = Date.now() + cartDelayMs; } response.writeHead(addStatus, { "Content-Type": "application/json" }); response.end(JSON.stringify({ items: [{ id: 123, variant_id: 123 }] })); return; } if (request.url === "/cart/clear.js" && request.method === "POST") { carted = false; response.writeHead(200, { "Content-Type": "application/json" }); response.end(JSON.stringify({ item_count: 0, items: [] })); return; } if (request.url === "/cart.js") { response.writeHead(200, { "Content-Type": "application/json" }); response.end(JSON.stringify(carted && Date.now() >= cartVisibleAt ? { item_count: 1, currency: "EUR", items: [{ variant_id: 123, product_title: "Fixture", final_line_price: 1000 }] } : { item_count: 0, currency: "EUR", items: [] })); return; } if (request.url === "/cart") { response.writeHead(303, { Location: request.method === "POST" ? "/checkouts/fixture" : "/pages/shop" }); response.end(); return; } if (request.url === "/checkout-form") { response.writeHead(200, { "Content-Type": "text/html" }); response.end('<!doctype html><label>Country/region<select name="country" autocomplete="shipping country"><option value="PT" selected>Portugal</option></select></label><label>Region<select name="region"><option value="Lisbon" selected>Lisbon</option></select></label><label>First name<input autocomplete="shipping given-name"></label><label>Last name<input autocomplete="shipping family-name"></label><label>Email<input autocomplete="shipping email"></label><label>Phone<input autocomplete="shipping tel" value="919 060 031"></label><label>Street address city<input name="opaque-city" autocomplete="shipping address-level2"></label><label>Address<input name="opaque-address" autocomplete="shipping address-line1"></label><label>Postal code<input name="opaque-postal" autocomplete="shipping postal-code"></label>'); return; } response.writeHead(200, { "Content-Type": "text/html" }); response.end("<!doctype html><title>fixture</title>"); }); await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve)); const address = server.address(); if (!address || typeof address === "string") throw new Error("Fixture did not start."); origin = `http://127.0.0.1:${address.port}`; profile = await mkdtemp(join(tmpdir(), "copify-direct-cart-")); close = () => new Promise((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); });
  afterAll(async () => { await close?.(); if (profile) await rm(profile, { recursive: true, force: true }); });
  it("adds one exact variant and verifies identity and price", async () => { const executablePath = findChromeExecutable(); if (!executablePath) throw new Error("Chrome is required."); const context = await chromium.launchPersistentContext(profile, { executablePath, headless: true }); try { const page = context.pages()[0] ?? await context.newPage(); await page.goto(`${origin}/pages/shop`); addStatus = 200; carted = false; cartDelayMs = 0; addAttempts = 0; const started = performance.now(); expect(await submitDirectCart(page, "123")).toBe("ADDED"); expect(performance.now() - started).toBeLessThan(400); expect(addAttempts).toBe(1); const cart = await page.evaluate(async () => (await fetch("/cart.js")).json()); expect(parseShopifyCart(cart, "Fixture", "123")).toMatchObject({ state: "ITEMS", itemCount: 1, hasVariant: true, currency: "EUR", priceMinor: 1000 }); } finally { await context.close(); } });
  it("waits for a successful cart mutation to become visible", async () => { const executablePath = findChromeExecutable(); if (!executablePath) throw new Error("Chrome is required."); const context = await chromium.launchPersistentContext(profile, { executablePath, headless: true }); try { const page = context.pages()[0] ?? await context.newPage(); await page.goto(`${origin}/pages/shop`); addStatus = 200; carted = false; cartDelayMs = 600; expect(await submitDirectCart(page, "123")).toBe("ADDED"); const started = performance.now(); expect(await waitForExactVisibleCart(page, "Fixture", "123", 2_000)).toMatchObject({ state: "ITEMS", hasVariant: true }); expect(performance.now() - started).toBeGreaterThanOrEqual(500); } finally { cartDelayMs = 0; await context.close(); } });
  it("reads the browser cart document without following the empty-cart redirect", async () => { const executablePath = findChromeExecutable(); if (!executablePath) throw new Error("Chrome is required."); const context = await chromium.launchPersistentContext(profile, { executablePath, headless: true }); try { const page = context.pages()[0] ?? await context.newPage(); carted = false; expect(await inspectBrowserCartDocument(page, "", origin)).toEqual({ state: "EMPTY" }); expect(page.url()).toBe(`${origin}/cart.js`); } finally { await context.close(); } });
  it("submits Shopify's supported cart form when the theme has no checkout control", async () => { const executablePath = findChromeExecutable(); if (!executablePath) throw new Error("Chrome is required."); const context = await chromium.launchPersistentContext(profile, { executablePath, headless: true }); try { const page = context.pages()[0] ?? await context.newPage(); await page.goto(`${origin}/pages/shop`); await goToCheckout(page, `${origin}/products/fixture`); expect(page.url()).toBe(`${origin}/checkouts/fixture`); } finally { await context.close(); } });
  it("reuses formatted values and prioritizes prefixed autocomplete tokens over misleading labels", async () => { const executablePath = findChromeExecutable(); if (!executablePath) throw new Error("Chrome is required."); const context = await chromium.launchPersistentContext(profile, { executablePath, headless: true }); try { const page = context.pages()[0] ?? await context.newPage(); await page.goto(`${origin}/checkout-form`); await fillShipping(page, { fullName: "Vicente Simoes", email: "vicente@example.test", phone: "+351 919060031", address1: "1 Main Street", postalCode: "1000-001", city: "Lisbon", region: "Lisbon", country: "PT" }); const values = await page.locator("input").evaluateAll((inputs) => Object.fromEntries(inputs.map((input) => [(input as HTMLInputElement).autocomplete, (input as HTMLInputElement).value]))); expect(values).toMatchObject({ "shipping given-name": "Vicente", "shipping family-name": "Simoes", "shipping email": "vicente@example.test", "shipping tel": "919 060 031", "shipping address-line1": "1 Main Street", "shipping postal-code": "1000-001", "shipping address-level2": "Lisbon" }); } finally { await context.close(); } }, 15_000);
  it("classifies unsupported, protection, unavailable, and uncertain responses without retrying", async () => { const executablePath = findChromeExecutable(); if (!executablePath) throw new Error("Chrome is required."); const context = await chromium.launchPersistentContext(profile, { executablePath, headless: true }); try { const page = context.pages()[0] ?? await context.newPage(); await page.goto(`${origin}/pages/shop`); for (const [status, expected] of [[404, "UNSUPPORTED"], [429, "PROTECTION"], [422, "UNAVAILABLE"], [500, "UNCERTAIN"]] as const) { addStatus = status; carted = false; addAttempts = 0; expect(await submitDirectCart(page, "123")).toBe(expected); expect(addAttempts).toBe(1); expect(carted).toBe(false); } } finally { await context.close(); } });
});
