import { createServer } from "node:http";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { chromium } from "rebrowser-playwright";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { findChromeExecutable } from "./network";
import { parseShopifyCart, submitDirectCart } from "./runner";

const enabled = process.env.COPIFY_DIRECT_CART_SMOKE === "1";
describe.skipIf(!enabled)("verified direct-cart smoke", () => {
  let origin = ""; let profile = ""; let close: (() => Promise<void>) | undefined; let carted = false; let addStatus = 200; let addAttempts = 0;
  beforeAll(async () => { const server = createServer((request, response) => { if (request.url === "/cart/add.js" && request.method === "POST") { addAttempts += 1; if (addStatus === 200) carted = true; response.writeHead(addStatus, { "Content-Type": "application/json" }); response.end("{}"); return; } if (request.url === "/cart.js") { response.writeHead(200, { "Content-Type": "application/json" }); response.end(JSON.stringify(carted ? { item_count: 1, currency: "EUR", items: [{ variant_id: 123, product_title: "Fixture", final_line_price: 1000 }] } : { item_count: 0, currency: "EUR", items: [] })); return; } response.writeHead(200, { "Content-Type": "text/html" }); response.end("<!doctype html><title>fixture</title>"); }); await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve)); const address = server.address(); if (!address || typeof address === "string") throw new Error("Fixture did not start."); origin = `http://127.0.0.1:${address.port}`; profile = await mkdtemp(join(tmpdir(), "copify-direct-cart-")); close = () => new Promise((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); });
  afterAll(async () => { await close?.(); if (profile) await rm(profile, { recursive: true, force: true }); });
  it("adds one exact variant and verifies identity and price", async () => { const executablePath = findChromeExecutable(); if (!executablePath) throw new Error("Chrome is required."); const context = await chromium.launchPersistentContext(profile, { executablePath, headless: true }); try { const page = context.pages()[0] ?? await context.newPage(); await page.goto(`${origin}/pages/shop`); addStatus = 200; carted = false; addAttempts = 0; const started = performance.now(); expect(await submitDirectCart(page, "123")).toBe("ADDED"); expect(performance.now() - started).toBeLessThan(400); expect(addAttempts).toBe(1); const cart = await page.evaluate(async () => (await fetch("/cart.js")).json()); expect(parseShopifyCart(cart, "Fixture", "123")).toMatchObject({ state: "ITEMS", itemCount: 1, hasVariant: true, currency: "EUR", priceMinor: 1000 }); } finally { await context.close(); } });
  it("classifies unsupported, protection, unavailable, and uncertain responses without retrying", async () => { const executablePath = findChromeExecutable(); if (!executablePath) throw new Error("Chrome is required."); const context = await chromium.launchPersistentContext(profile, { executablePath, headless: true }); try { const page = context.pages()[0] ?? await context.newPage(); await page.goto(`${origin}/pages/shop`); for (const [status, expected] of [[404, "UNSUPPORTED"], [429, "PROTECTION"], [422, "UNAVAILABLE"], [500, "UNCERTAIN"]] as const) { addStatus = status; carted = false; addAttempts = 0; expect(await submitDirectCart(page, "123")).toBe(expected); expect(addAttempts).toBe(1); expect(carted).toBe(false); } } finally { await context.close(); } });
});
