import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import type { BrowserProfile, ProxyBenchmark, ProxyProfile, SessionSnapshot } from "@copify/shared";
import "./styles.css";

type Notice = { kind: "error" | "info"; message: string } | null;
type ProxyDraft = { name: string; provider: ProxyProfile["provider"]; type: ProxyProfile["type"]; protocol: ProxyProfile["protocol"]; host: string; port: number; username: string; password: string; expectedCountry?: string; expectedCity?: string; enabled: boolean };
const blankProxy = (): ProxyDraft => ({ name: "", provider: "custom", type: "residential-sticky", protocol: "http", host: "", port: 8080, username: "", password: "", expectedCountry: undefined, expectedCity: undefined, enabled: true });

function App() {
  const [profiles, setProfiles] = useState<BrowserProfile[]>([]); const [proxies, setProxies] = useState<ProxyProfile[]>([]); const [sessions, setSessions] = useState<Record<string, SessionSnapshot>>({});
  const [benchmarks, setBenchmarks] = useState<Record<string, ProxyBenchmark[]>>({}); const [profileName, setProfileName] = useState(""); const [proxyDraft, setProxyDraft] = useState<ProxyDraft>(blankProxy()); const [editingProxyId, setEditingProxyId] = useState<string | null>(null);
  const [probeUrl, setProbeUrl] = useState(""); const [notice, setNotice] = useState<Notice>(null); const [busy, setBusy] = useState(false); const [testing, setTesting] = useState<string | null>(null);

  const reload = async (): Promise<void> => {
    const [profileResult, proxyResult, sessionResult, settingResult] = await Promise.all([window.copify.profiles.list(), window.copify.proxies.list(), window.copify.sessions.list(), window.copify.settings.getNetworkProbe()]);
    if (!profileResult.ok) { setNotice({ kind: "error", message: profileResult.error }); return; } if (!proxyResult.ok) { setNotice({ kind: "error", message: proxyResult.error }); return; }
    setProfiles(profileResult.value); setProxies(proxyResult.value); if (sessionResult.ok) setSessions(Object.fromEntries(sessionResult.value.map((session) => [session.profileId, session]))); if (settingResult.ok) setProbeUrl(settingResult.value.probeUrl);
    const entries = await Promise.all([null, ...proxyResult.value.map((proxy) => proxy.id)].map(async (id) => [id ?? "direct", await window.copify.proxies.benchmarks(id)] as const));
    const nextBenchmarks: Record<string, ProxyBenchmark[]> = {};
    for (const [key, value] of entries) if (value.ok) nextBenchmarks[key] = value.value;
    setBenchmarks(nextBenchmarks);
  };
  useEffect(() => { void reload(); return window.copify.sessions.onChanged((snapshot) => setSessions((current) => ({ ...current, [snapshot.profileId]: snapshot }))); }, []);

  const activeCount = useMemo(() => Object.values(sessions).filter((session) => ["STARTING", "READY", "STOPPING"].includes(session.state)).length, [sessions]);
  const execute = async (operation: () => Promise<{ ok: boolean; error?: string }>, success?: string): Promise<void> => { setBusy(true); setNotice(null); try { const response = await operation(); if (!response.ok) setNotice({ kind: "error", message: response.error ?? "Operation failed." }); else if (success) setNotice({ kind: "info", message: success }); } finally { setBusy(false); await reload(); } };
  const session = (profileId: string): SessionSnapshot => sessions[profileId] ?? { profileId, state: "STOPPED", error: null, route: { kind: "direct", verification: { status: "PENDING", publicIp: null, country: null, city: null, verifiedAt: null, message: null } }, updatedAt: 0 };
  const latest = (id: string) => benchmarks[id]?.[0];

  const saveProxy = async (event: React.FormEvent): Promise<void> => { event.preventDefault(); const input = { ...proxyDraft, expectedCountry: proxyDraft.expectedCountry?.trim() || null, expectedCity: proxyDraft.expectedCity?.trim() || null, username: proxyDraft.username || undefined, password: proxyDraft.password || undefined };
    await execute(() => editingProxyId ? window.copify.proxies.update(editingProxyId, input) : window.copify.proxies.create(input), editingProxyId ? "Proxy profile updated." : "Proxy profile created."); if (!editingProxyId) setProxyDraft(blankProxy()); setEditingProxyId(null); };
  const editProxy = (proxy: ProxyProfile) => { setEditingProxyId(proxy.id); setProxyDraft({ name: proxy.name, provider: proxy.provider, type: proxy.type, protocol: proxy.protocol, host: proxy.host, port: proxy.port, username: "", password: "", expectedCountry: proxy.expectedCountry ?? undefined, expectedCity: proxy.expectedCity ?? undefined, enabled: proxy.enabled }); window.scrollTo({ top: document.body.scrollHeight, behavior: "smooth" }); };
  const clearCredential = (proxy: ProxyProfile, field: "username" | "password") => { if (window.confirm(`Clear the saved proxy ${field}?`)) void execute(() => window.copify.proxies.update(proxy.id, { [field]: null }), `Proxy ${field} cleared.`); };
  const testRoute = async (id: string | null) => { const key = id ?? "direct"; setTesting(key); setNotice(null); try { const response = await window.copify.proxies.test(id); setNotice(response.ok ? { kind: "info", message: `${id ? "Proxy" : "Direct network"} benchmark completed.` } : { kind: "error", message: response.error }); } finally { setTesting(null); await reload(); } };

  return <main>
    <header><div><p className="eyebrow">COPIFY / V0.2</p><h1>Browser operations console</h1></div><div className="summary"><strong>{activeCount}</strong> active sessions</div></header>
    <section className="toolbar"><button disabled={busy || !profiles.some((p) => p.enabled)} onClick={() => void execute(() => window.copify.sessions.openAll())}>Open all</button><button className="secondary" disabled={busy || activeCount === 0} onClick={() => void execute(() => window.copify.sessions.closeAll())}>Close all</button></section>
    {notice && <p className={`notice ${notice.kind}`}>{notice.message}</p>}

    <section className="panel"><div className="section-title"><div><p className="eyebrow">NETWORK HEALTH</p><h2>Direct network</h2></div><button disabled={busy || testing !== null} onClick={() => void testRoute(null)}>{testing === "direct" ? "Testing…" : "Test direct route"}</button></div><Benchmark benchmark={latest("direct")} /><BenchmarkHistory benchmarks={benchmarks.direct ?? []} /><form className="inline-form" onSubmit={(event) => { event.preventDefault(); void execute(() => window.copify.settings.updateNetworkProbe({ probeUrl }), "Network probe updated."); }}><input value={probeUrl} onChange={(event) => setProbeUrl(event.target.value)} aria-label="HTTPS network probe URL" /><button className="secondary" disabled={busy || !probeUrl}>Save probe URL</button></form></section>

    <section className="new-profile"><h2>Browser profiles</h2><form onSubmit={(event) => { event.preventDefault(); void execute(async () => { const response = await window.copify.profiles.create({ name: profileName }); if (response.ok) setProfileName(""); return response; }, "Browser profile created."); }}><input value={profileName} onChange={(event) => setProfileName(event.target.value)} maxLength={80} placeholder="e.g. Home session" aria-label="Profile name" /><button disabled={busy || !profileName.trim()} type="submit">Add profile</button></form></section>
    <section className="profiles" aria-label="Browser profiles">{profiles.length === 0 && <div className="empty">Create a profile to launch its isolated, persistent Chrome session.</div>}{profiles.map((profile) => { const current = session(profile.id); const active = ["STARTING", "READY", "STOPPING"].includes(current.state); return <article key={profile.id} className="profile-card"><div className="profile-title"><div><h3>{profile.name}</h3><p>{profile.enabled ? "Enabled" : "Disabled"} · {current.route.kind === "proxy" ? current.route.proxyName : "Direct network"}</p></div><span className={`state ${current.state.toLowerCase()}`}>{current.state}</span></div><Route route={current.route} />{current.error && <p className="error-detail">{current.error.code}: {current.error.message}</p>}<div className="actions"><label className="select-label">Route<select value={profile.proxyProfileId ?? ""} disabled={busy || active} onChange={(event) => void execute(() => window.copify.profiles.update(profile.id, { proxyProfileId: event.target.value || null }), "Browser route updated.")}><option value="">Direct network</option>{proxies.map((proxy) => <option key={proxy.id} value={proxy.id} disabled={!proxy.enabled}>{proxy.name}{proxy.enabled ? "" : " (disabled)"}</option>)}</select></label><button disabled={busy || !profile.enabled || active} onClick={() => void execute(() => window.copify.sessions.open(profile.id))}>Open</button><button className="secondary" disabled={busy || !active} onClick={() => void execute(() => window.copify.sessions.close(profile.id))}>Close</button><button className="secondary" disabled={busy || !profile.enabled || current.state === "STARTING" || current.state === "STOPPING"} onClick={() => void execute(() => window.copify.sessions.restart(profile.id))}>Restart</button><button className="text" disabled={busy || active} onClick={() => { const name = window.prompt("Profile name", profile.name)?.trim(); if (name && name !== profile.name) void execute(() => window.copify.profiles.update(profile.id, { name })); }}>Rename</button><button className="text" disabled={busy || active} onClick={() => void execute(() => window.copify.profiles.update(profile.id, { enabled: !profile.enabled }))}>{profile.enabled ? "Disable" : "Enable"}</button><button className="danger" disabled={busy || active} onClick={() => { if (window.confirm(`Remove “${profile.name}” from Copify? Its Chrome data will stay on disk.`)) void execute(() => window.copify.profiles.remove(profile.id)); }}>Remove</button></div></article>; })}</section>

    <section className="proxy-section"><div className="section-title"><div><p className="eyebrow">OPTIONAL ROUTES</p><h2>Proxy profiles</h2></div><span className="summary">Credentials are encrypted and never shown again.</span></div><div className="profiles">{proxies.length === 0 && <div className="empty">No proxies configured. Every browser uses your direct network until you assign one.</div>}{proxies.map((proxy) => <article key={proxy.id} className="profile-card"><div className="profile-title"><div><h3>{proxy.name}</h3><p>{proxy.protocol.toUpperCase()} · {proxy.type} · {proxy.host}:{proxy.port} · {proxy.enabled ? "Enabled" : "Disabled"}</p></div><span className={`state ${latest(proxy.id)?.status.toLowerCase() ?? ""}`}>{latest(proxy.id)?.status ?? "UNTESTED"}</span></div><p className="muted">{proxy.usernameConfigured ? "Username saved" : "No username"} · {proxy.passwordConfigured ? "Password saved" : "No password"}{proxy.expectedCountry ? ` · Expected ${proxy.expectedCountry}${proxy.expectedCity ? ` / ${proxy.expectedCity}` : ""}` : ""}</p><Benchmark benchmark={latest(proxy.id)} /><BenchmarkHistory benchmarks={benchmarks[proxy.id] ?? []} /><div className="actions"><button disabled={busy || testing !== null} onClick={() => void testRoute(proxy.id)}>{testing === proxy.id ? "Testing…" : "Test proxy"}</button><button className="secondary" disabled={busy} onClick={() => editProxy(proxy)}>Edit</button><button className="text" disabled={busy} onClick={() => void execute(() => window.copify.proxies.update(proxy.id, { enabled: !proxy.enabled }))}>{proxy.enabled ? "Disable" : "Enable"}</button>{proxy.usernameConfigured && <button className="text" disabled={busy} onClick={() => clearCredential(proxy, "username")}>Clear username</button>}{proxy.passwordConfigured && <button className="text" disabled={busy} onClick={() => clearCredential(proxy, "password")}>Clear password</button>}<button className="danger" disabled={busy} onClick={() => { if (window.confirm(`Remove “${proxy.name}”? Assigned inactive profiles will return to direct networking.`)) void execute(() => window.copify.proxies.remove(proxy.id)); }}>Remove</button></div></article>)}</div>
      <form className="proxy-form" onSubmit={(event) => void saveProxy(event)}><div className="section-title"><h3>{editingProxyId ? "Edit proxy profile" : "Add proxy profile"}</h3>{editingProxyId && <button className="text" type="button" onClick={() => { setEditingProxyId(null); setProxyDraft(blankProxy()); }}>Cancel edit</button>}</div><input required value={proxyDraft.name} onChange={(event) => setProxyDraft({ ...proxyDraft, name: event.target.value })} placeholder="Proxy name" /><select value={proxyDraft.provider} onChange={(event) => setProxyDraft({ ...proxyDraft, provider: event.target.value as ProxyDraft["provider"] })}><option value="custom">Custom</option><option value="brightdata">Bright Data</option><option value="decodo">Decodo</option><option value="oxylabs">Oxylabs</option></select><select value={proxyDraft.type} onChange={(event) => setProxyDraft({ ...proxyDraft, type: event.target.value as ProxyDraft["type"] })}><option value="residential-sticky">Sticky residential</option><option value="isp-static">Static ISP</option><option value="datacenter">Datacenter</option><option value="home">Home</option></select><select value={proxyDraft.protocol} onChange={(event) => setProxyDraft({ ...proxyDraft, protocol: event.target.value as ProxyDraft["protocol"] })}><option value="http">HTTP</option><option value="https">HTTPS</option><option value="socks5">SOCKS5</option></select><input required value={proxyDraft.host} onChange={(event) => setProxyDraft({ ...proxyDraft, host: event.target.value })} placeholder="Host" /><input required type="number" min="1" max="65535" value={proxyDraft.port} onChange={(event) => setProxyDraft({ ...proxyDraft, port: Number(event.target.value) })} placeholder="Port" /><input type="text" autoComplete="off" value={proxyDraft.username} onChange={(event) => setProxyDraft({ ...proxyDraft, username: event.target.value })} placeholder={editingProxyId ? "New username (leave blank to keep)" : "Username (optional)"} /><input type="password" autoComplete="new-password" value={proxyDraft.password} onChange={(event) => setProxyDraft({ ...proxyDraft, password: event.target.value })} placeholder={editingProxyId ? "New password (leave blank to keep)" : "Password (optional)"} /><input maxLength={2} value={proxyDraft.expectedCountry ?? ""} onChange={(event) => setProxyDraft({ ...proxyDraft, expectedCountry: event.target.value.toUpperCase() || undefined })} placeholder="Country (PT)" /><input value={proxyDraft.expectedCity ?? ""} onChange={(event) => setProxyDraft({ ...proxyDraft, expectedCity: event.target.value || undefined })} placeholder="City (optional)" /><label className="check"><input type="checkbox" checked={proxyDraft.enabled} onChange={(event) => setProxyDraft({ ...proxyDraft, enabled: event.target.checked })} /> Enabled</label><button disabled={busy} type="submit">{editingProxyId ? "Save proxy" : "Add proxy"}</button></form></section>
  </main>;
}

function Route({ route }: { route: SessionSnapshot["route"] }) { const check = route.verification; return <p className={`route ${check.status.toLowerCase()}`}>{check.status === "PENDING" ? "Route awaiting verification" : check.publicIp ? `${check.status} · ${check.publicIp}${check.country ? ` · ${check.country}` : ""}${check.city ? ` / ${check.city}` : ""}` : `${check.status} · ${check.message ?? "No public route confirmed"}`}</p>; }
function Benchmark({ benchmark }: { benchmark?: ProxyBenchmark }) { if (!benchmark) return <p className="muted">No benchmark yet.</p>; return <div className={`benchmark ${benchmark.status.toLowerCase()}`}><span><b>{benchmark.qualityScore}</b> / 100</span><span>{benchmark.publicIp ?? "No IP"}</span><span>{benchmark.medianLatencyMs === null ? "—" : `${Math.round(benchmark.medianLatencyMs)} ms median`}</span><span>{benchmark.jitterMs === null ? "—" : `${Math.round(benchmark.jitterMs)} ms jitter`}</span><span>{Math.round(benchmark.failureRate * 100)}% failures</span><span>{benchmark.ipStable ? "Stable IP" : "Unstable IP"}</span>{benchmark.errorMessage && <span>{benchmark.errorMessage}</span>}</div>; }
function BenchmarkHistory({ benchmarks }: { benchmarks: ProxyBenchmark[] }) { if (benchmarks.length < 2) return null; return <div className="history"><span>Recent tests</span>{benchmarks.slice(1).map((benchmark) => <span key={benchmark.id}>{new Date(benchmark.completedAt).toLocaleString()} · {benchmark.status} · {benchmark.qualityScore}/100</span>)}</div>; }
createRoot(document.getElementById("root")!).render(<App />);
