import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import type { RunDetail } from "@copify/shared";
import { deriveMetrics, percentile } from "./analytics";

describe("historical metric derivation", () => {
  it("uses monotonic timestamps and preserves missing phases as null", () => {
    const runId = randomUUID(); const sessionId = randomUUID(); const profileId = randomUUID(); const event = (type: string, elapsedNs: string, runSessionId: string | null, payload: Record<string, unknown> = {}) => ({ id: randomUUID(), runId, runSessionId, wallTimeMs: 1, elapsedNs, type, stateBefore: null, stateAfter: null, payload });
    const detail = { run: { id: runId, name: "Drop", diagnosticLevel: "NORMAL", executionMode: "CHECKOUT", purchaseMode: "LEGACY_MANUAL", maxCheckouts: "UNLIMITED", status: "COMPLETED", startedAt: 1, endedAt: 2, environment: { appVersion: "0.11.0", schemaVersion: 16, osVersion: "win", chromeVersion: null, playwrightVersion: "test", capturedAt: 1 }, targetSnapshot: null, discoverySnapshot: null, createdAt: 1, updatedAt: 2 }, sessions: [{ id: sessionId, runId, browserProfileId: profileId, browserProfileName: "PT", route: { kind: "direct", verification: { status: "VERIFIED", publicIp: null, country: null, city: null, verifiedAt: 1, message: null } }, shippingProfile: { shippingProfileId: null, name: null, country: null, complete: false }, paymentProfile: { paymentProfileId: null, label: null, kind: null, configured: false, path: "NONE" }, checkoutMode: "ASSISTED", quotaOutcome: "NONE", orderIndex: null, captchaStrategy: "MANUAL_HARVESTER", captchaProvider: null, assistedEligible: true, executionState: "ENDED", checkpointReason: null, status: "ENDED", startedAt: 1, endedAt: 2, finalError: null }], events: [event("TARGET_MONITOR_STARTED", "9007199254740993000", null), event("DISCOVERY_MESH_WINNER", "9007199255740993000", null, { source: "collection" }), event("VARIANT_SELECTED", "9007199255740993100", sessionId), event("CART_CONFIRMED", "9007199256740993000", sessionId), event("READY_TO_CONFIRM", "9007199257740993000", sessionId)], artifacts: [] } satisfies RunDetail;
    const metrics = deriveMetrics(detail); expect(metrics.run.monitorToDetectMs).toBe(1_000); expect(metrics.sessions[0].detectToCartMs).toBe(1_000); expect(metrics.sessions[0].cartToCheckoutMs).toBeNull(); expect(metrics.sessions[0].observedOutcome).toBe("READY_TO_CONFIRM");
  });
  it("uses deterministic nearest-rank percentiles", () => { expect(percentile([1, 2, 3, 4], .5)).toBe(2); expect(percentile([1, 2, 3, 4], .95)).toBe(4); expect(percentile([], .5)).toBeNull(); });
});
